//
//  BithumbCurrencies.swift
//  CoinCheck
//
//  Created by Min Kyeong Tae on 30/06/2019.
//  Copyright © 2019 Min Kyeong Tae. All rights reserved.
//

import UIKit

enum ButhumbCurrencyName: String {
    case btc = "BTC"
    case eth = "ETH"
    case dash = "DASH"
    case ltc = "LTC"
    case etc = "ETC"
    case xrp = "XRP"
    case bch = "BCH"
    case xmr = "XMR"
    case zec = "ZEC"
    case qtum = "QTUM"
    case btg = "BTG"
    case eos = "EOS"
    case icx = "ICX"
    case vet = "VET"
    case trx = "TRX"
    case elf = "ELF"
    case mith = "MITH"
    case mco = "MCO"
    case omg = "OMG"
    case knc = "KNC"
    case gnt = "GNT"
    case zil = "ZIL"
    case ethos = "ETHOS"
    case pay = "PAY"
    case wax = "WAX"
    case powr = "POWR"
    case lrc = "LRC"
    case gto = "GTO"
    case steem = "STEEM"
    case strat = "STRAT"
    case zrx = "ZRX"
    case rep = "REP"
    case ae = "AE"
    case xem = "XEM"
    case snt = "SNT"
    case ada = "ADA"
    case ppt = "PPT"
    case ctxc = "CTXC"
    case cmt = "CMT"
    case theta = "THETA"
    case wtc = "WTC"
    case itc = "ITC"
    case dataTRUE = "TRUE"
    case abt = "ABT"
    case rnt = "RNT"
    case ply = "PLY"
    case waves = "WAVES"
    case link = "LINK"
    case enj = "ENJ"
    case pst = "PST"
    case salt = "SALT"
    case rdn = "RDN"
    case loom = "LOOM"
    case pivx = "PIVX"
    case ins = "INS"
    case bcd = "BCD"
    case bznt = "BZNT"
    case xlm = "XLM"
    case ocn = "OCN"
    case bsv = "BSV"
    case tmtg = "TMTG"
    case bat = "BAT"
    case wet = "WET"
    case xvg = "XVG"
    case iost = "IOST"
    case poly = "POLY"
    case hc = "HC"
    case rom = "ROM"
    case amo = "AMO"
    case etz = "ETZ"
    case arn = "ARN"
    case apis = "APIS"
    case mtl = "MTL"
    case dacc = "DACC"
    case dac = "DAC"
    case bhp = "BHP"
    case btt = "BTT"
    case hdac = "HDAC"
    case npxs = "NPXS"
    case auto = "AUTO"
    case gxc = "GXC"
    case orbs = "ORBS"
    case valor = "VALOR"
    case con = "CON"
    case ankr = "ANKR"
    case mix = "MIX"
}

class BithumbCurrencies {
    static let bithumbCurrencyNameString: [String] = ["BTC","ETH","DASH","LTC","ETC","XRP","BCH","XMR","ZEC","QTUM","BTG","EOS","ICX","VET","TRX","ELF","MITH","MCO","OMG","KNC","GNT","ZIL","ETHOS","PAY","WAX","POWR","LRC","GTO","STEEM","STRAT","ZRX","REP","AE","XEM","SNT","ADA","PPT","CTXC","CMT","THETA","WTC","ITC","TRUE","ABT","RNT","PLY","WAVES","LINK","ENJ","PST","SALT","RDN","LOOM","PIVX","INS","BCD","BZNT","XLM","OCN","BSV","TMTG","BAT","WET","XVG","IOST","POLY","HC","ROM","AMO","ETZ","ARN","APIS","MTL","DACC","DAC","BHP","BTT","HDAC","NPXS","AUTO","GXC","ORBS","VALOR","CON","ANKR","MIX"]
//
//    static let btc = BithumbCurrency(name: "BTC")
//    static let eth = BithumbCurrency(name: "ETH")
//    static let dash = BithumbCurrency(name: "DASH")
//    static let ltc = BithumbCurrency(name: "LTC")
//    static let etc = BithumbCurrency(name: "ETC")
//    static let xrp = BithumbCurrency(name: "XRP")
//    static let bch = BithumbCurrency(name: "BCH")
//    static let xmr = BithumbCurrency(name: "XMR")
//    static let zec = BithumbCurrency(name: "ZEC")
//    static let qtum = BithumbCurrency(name: "QTUM")
//    static let btg = BithumbCurrency(name: "BTG")
//    static let eos = BithumbCurrency(name: "EOS")
//    static let icx = BithumbCurrency(name: "ICX")
//    static let vet = BithumbCurrency(name: "VET")
//    static let trx = BithumbCurrency(name: "TRX")
//    static let elf = BithumbCurrency(name: "ELF")
//    static let mith = BithumbCurrency(name: "MITH")
//    static let mco = BithumbCurrency(name: "MCO")
//    static let omg = BithumbCurrency(name: "OMG")
//    static let knc = BithumbCurrency(name: "KNC")
//    static let gnt = BithumbCurrency(name: "GNT")
//    static let zil = BithumbCurrency(name: "ZIL")
//    static let ethos = BithumbCurrency(name: "ETHOS")
//    static let pay = BithumbCurrency(name: "PAY")
//    static let wax = BithumbCurrency(name: "WAX")
//    static let powr = BithumbCurrency(name: "POWR")
//    static let lrc = BithumbCurrency(name: "LRC")
//    static let gto = BithumbCurrency(name: "GTO")
//    static let steem = BithumbCurrency(name: "STEEM")
//    static let strat = BithumbCurrency(name: "STRAT")
//    static let zrx = BithumbCurrency(name: "ZRX")
//    static let rep = BithumbCurrency(name: "REP")
//    static let ae = BithumbCurrency(name: "AE")
//    static let xem = BithumbCurrency(name: "XEM")
//    static let snt = BithumbCurrency(name: "SNT")
//    static let ada = BithumbCurrency(name: "ADA")
//    static let ppt = BithumbCurrency(name: "PPT")
//    static let ctxc = BithumbCurrency(name: "CTXC")
//    static let cmt = BithumbCurrency(name: "CMT")
//    static let theta = BithumbCurrency(name: "THETA")
//    static let wtc = BithumbCurrency(name: "WTC")
//    static let itc = BithumbCurrency(name: "ITC")
//    static let dataTRUE = BithumbCurrency(name: "TRUE")
//    static let abt = BithumbCurrency(name: "ABT")
//    static let rnt = BithumbCurrency(name: "RNT")
//    static let ply = BithumbCurrency(name: "PLY")
//    static let waves = BithumbCurrency(name: "WAVES")
//    static let link = BithumbCurrency(name: "LINK")
//    static let enj = BithumbCurrency(name: "ENJ")
//    static let pst = BithumbCurrency(name: "PST")
//    static let salt = BithumbCurrency(name: "SALT")
//    static let rdn = BithumbCurrency(name: "RDN")
//    static let loom = BithumbCurrency(name: "LOOM")
//    static let pivx = BithumbCurrency(name: "PIVX")
//    static let ins = BithumbCurrency(name: "INS")
//    static let bcd = BithumbCurrency(name: "BCD")
//    static let bznt = BithumbCurrency(name: "BZNT")
//    static let xlm = BithumbCurrency(name: "XLM")
//    static let ocn = BithumbCurrency(name: "OCN")
//    static let bsv = BithumbCurrency(name: "BSV")
//    static let tmtg = BithumbCurrency(name: "TMTG")
//    static let bat = BithumbCurrency(name: "BAT")
//    static let wet = BithumbCurrency(name: "WET")
//    static let xvg = BithumbCurrency(name: "XVG")
//    static let iost = BithumbCurrency(name: "IOST")
//    static let poly = BithumbCurrency(name: "POLY")
//    static let hc = BithumbCurrency(name: "HC")
//    static let rom = BithumbCurrency(name: "ROM")
//    static let amo = BithumbCurrency(name: "AMO")
//    static let etz = BithumbCurrency(name: "ETZ")
//    static let arn = BithumbCurrency(name: "ARN")
//    static let apis = BithumbCurrency(name: "APIS")
//    static let mtl = BithumbCurrency(name: "MTL")
//    static let dacc = BithumbCurrency(name: "DACC")
//    static let dac = BithumbCurrency(name: "DAC")
//    static let bhp = BithumbCurrency(name: "BHP")
//    static let btt = BithumbCurrency(name: "BTT")
//    static let hdac = BithumbCurrency(name: "HDAC")
//    static let npxs = BithumbCurrency(name: "NPXS")
//    static let auto = BithumbCurrency(name: "AUTO")
//    static let gxc = BithumbCurrency(name: "GXC")
//    static let orbs = BithumbCurrency(name: "ORBS")
//    static let valor = BithumbCurrency(name: "VALOR")
//    static let con = BithumbCurrency(name: "CON")
//    static let ankr = BithumbCurrency(name: "ANKR")
//    static let mix = BithumbCurrency(name: "MIX")
}

struct BithumbCurrency {
    var currencyIndex: Int
    init(name: String){
        guard let currency = ButhumbCurrencyName(rawValue: name) else {
            currencyIndex=99
            return
        }
        switch currency {
        case .btc: currencyIndex=0
        case .eth: currencyIndex=1
        case .dash: currencyIndex=2
        case .ltc: currencyIndex=3
        case .etc: currencyIndex=4
        case .xrp: currencyIndex=5
        case .bch: currencyIndex=6
        case .xmr: currencyIndex=7
        case .zec: currencyIndex=8
        case .qtum: currencyIndex=9
        case .btg: currencyIndex=10
        case .eos: currencyIndex=11
        case .icx: currencyIndex=12
        case .vet: currencyIndex=13
        case .trx: currencyIndex=14
        case .elf: currencyIndex=15
        case .mith: currencyIndex=16
        case .mco: currencyIndex=17
        case .omg: currencyIndex=18
        case .knc: currencyIndex=19
        case .gnt: currencyIndex=20
        case .zil: currencyIndex=21
        case .ethos: currencyIndex=22
        case .pay: currencyIndex=23
        case .wax: currencyIndex=24
        case .powr: currencyIndex=25
        case .lrc: currencyIndex=26
        case .gto: currencyIndex=27
        case .steem: currencyIndex=28
        case .strat: currencyIndex=29
        case .zrx: currencyIndex=30
        case .rep: currencyIndex=31
        case .ae: currencyIndex=32
        case .xem: currencyIndex=33
        case .snt: currencyIndex=34
        case .ada: currencyIndex=35
        case .ppt: currencyIndex=36
        case .ctxc: currencyIndex=37
        case .cmt: currencyIndex=38
        case .theta: currencyIndex=39
        case .wtc: currencyIndex=40
        case .itc: currencyIndex=41
        case .dataTRUE: currencyIndex=42
        case .abt: currencyIndex=43
        case .rnt: currencyIndex=44
        case .ply: currencyIndex=45
        case .waves: currencyIndex=46
        case .link: currencyIndex=47
        case .enj: currencyIndex=48
        case .pst: currencyIndex=49
        case .salt: currencyIndex=50
        case .rdn: currencyIndex=51
        case .loom: currencyIndex=52
        case .pivx: currencyIndex=53
        case .ins: currencyIndex=54
        case .bcd: currencyIndex=55
        case .bznt: currencyIndex=56
        case .xlm: currencyIndex=57
        case .ocn: currencyIndex=58
        case .bsv: currencyIndex=59
        case .tmtg: currencyIndex=60
        case .bat: currencyIndex=61
        case .wet: currencyIndex=62
        case .xvg: currencyIndex=63
        case .iost: currencyIndex=64
        case .poly: currencyIndex=65
        case .hc: currencyIndex=66
        case .rom: currencyIndex=67
        case .amo: currencyIndex=68
        case .etz: currencyIndex=69
        case .arn: currencyIndex=70
        case .apis: currencyIndex=71
        case .mtl: currencyIndex=72
        case .dacc: currencyIndex=73
        case .dac: currencyIndex=74
        case .bhp: currencyIndex=75
        case .btt: currencyIndex=76
        case .hdac: currencyIndex=77
        case .npxs: currencyIndex=78
        case .auto: currencyIndex=79
        case .gxc: currencyIndex=80
        case .orbs: currencyIndex=81
        case .valor: currencyIndex=82
        case .con: currencyIndex=83
        case .ankr: currencyIndex=84
        case .mix: currencyIndex=85
        }
    }

}
